<?php

        require_once('conn.php');
        if(isset($_POST['submit_btn']))
        {
            $name = $_POST['user_name'];
            $email= $_POST['user_email'];
            $contact = $_POST['user_contact'];
            $profile = $_FILES['user_profile']['name'];//picture name
            $profile_temp = $_FILES['user_profile']['tmp_name'];//temporary name that generated by php and stored on temporary folder on the server
            $profile_location = 'profiles/'.$profile;
            $address = $_POST['address'];
            $merk_mobil = $_POST['merk_mobil'];
            $fasilitas_sopir = $_POST['fasilitas_sopir'];
            
            //insert data
            $insert_data = "INSERT INTO `simple_table`(`name`, `email`, `contact`, `profile`, `address`, `merk_mobil`, `fasilitas_sopir`) 
                            VALUES ('$name','$email','$contact','$profile','$address','$merk_mobil','$fasilitas_sopir')";
            move_uploaded_file($profile_temp, $profile_location);
            $insert_query = mysqli_query($conn,$insert_data);
            
            if($insert_query)
            {
                header('location: index.php');
            }
            else
            {
                echo 'Data Not Insert';
            }
        }
    ?>